import React,{useState,useEffect} from 'react'
import {Button,Grid} from '@material-ui/core'
import '../theme.css'
import axios from 'axios'
function Vnfdform(props) {
   const {setOpen}=props;


   const [id,setId]=useState('');
   const [name,setName]=useState('');
   const [sname,setSname]=useState('');
  
   function handlesubmit(e){
       e.preventDefault();
       console.log(id);
       console.log(name);
       console.log(sname);
      
       axios.post('/osm/nsd/v1/ns_descriptors_content/',
       {
        "nsd:nsd-catalog": {
          "nsd": [
            {
              "id": id,
              "name": name,
              "short-name": sname,
              "description": "Generated by OSM pacakage generator",
              "vendor": "OSM",
              "version": "1.0",
              "logo": "osm_2x.png",
              "constituent-vnfd": [
                {
                  "member-vnf-index": 1,
                  "vnfd-id-ref": "cirros_vnfd"
                }
              ],
              "vld": [
                {
                  "id": "cirros_2vnf_nsd_vld1",
                  "name": "cirros_2vnf_nsd_vld1",
                  "short-name": "cirros_2vnf_nsd_vld1",
                  "type": "ELAN",
                  "mgmt-network": "true",
                  "vim-network-name": "osm-ext",
                  "vnfd-connection-point-ref": [
                    {
                      "member-vnf-index-ref": 1,
                      "vnfd-id-ref": "cirros_vnfd",
                      "vnfd-connection-point-ref": "eth0"
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
       )
       .then(response=>{
           console.log(response)
       })
       setOpen(false);
   }
   

    return (
        <div>
           <form onSubmit={handlesubmit}>
              <div>
                  <label for="name" class="col-sm-2 col-form-label">Id<span class="star"> *</span></label>
                  <div class="col-sm-10">
                     <input type="text" required class="form-control"  value={id}
                        onChange={(e)=>setId(e.target.value)}/>
                  </div>
                </div>
                <div>
                  <label for="name" class="col-sm-2 col-form-label">Name<span class="star"> *</span></label>
                  <div class="col-sm-10">
                     <input type="text" required class="form-control"  value={name}
                        onChange={(e)=>setName(e.target.value)}/>
                  </div>
                </div>
                <div>
                  <label for="name" class="col-sm-2 col-form-label">Short Name<span class="star"> *</span></label>
                  <div class="col-sm-10">
                     <input type="text" required class="form-control"  value={sname}
                        onChange={(e)=>setSname(e.target.value)}/>
                  </div>
                </div>
            

              <Grid
                container
                direction="row"
                justify="space-between"
                alignItems="baseline"
                >
                      
                <Button type="reset" color="default" variant="contained">
                    Reset
                </Button>
          
               <Button type="submit"  color="primary" variant="contained" >
                    Create
                 </Button>
              

              </Grid>

            
  
            </form>
        </div>
    )
}

export default Vnfdform
